### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nagimov**
add link to docker hub

### CODE REVIEW

**Comment by pixelbrackets** [comment]
Hey, thanks for the PR. I understand the idea, but the Agendav project can not endorse a docker image which is not maintained by agendav  itself. The linked image is not up to date and maintained by a user which has not contact options. 

However we could change the link to something more generic like „Agendav offers no official docker image yet. You may use docker images provided by community instead, see https://hub.docker.com/search?q=agendav“.

**Comment by nagimov** [comment]
Hi @pixelbrackets,

Sorry this PR is >1yr old and outdated.

The image on the docker-hub is out-of-date. Docker's new policy only allows paid accounts to utilize automatic builds, so I can't update that image without uploading unverifiable binary blobs. More info [here](https://github.com/nagimov/agendav-docker/issues/4#issuecomment-1207130521). I am not taking down the docker-hub image since it's still actively used (94k+ pulls as of today). I should update its README and point it to the up-to-date version though.

I now keep the up-to-date images at [GHCR](https://ghcr.io/nagimov/agendav-docker). Github container registry provides auto-builds and publishes build logs (e.g. [here](https://github.com/nagimov/agendav-docker/runs/7702779613?check_suite_focus=true)). This allows anyone to inspect the build for malicious code.

If you'd like to include a link to the updated docker image, I can change this PR to include the [URL of GHCR package](https://ghcr.io/nagimov/agendav-docker), or a [github package search query](https://github.com/search?package_type=container&q=agendav&type=RegistryPackages) (this image is still the only result there). [Docker-hub search query](https://hub.docker.com/search?q=agendav) is full of images without `Dockerfile` source provided and should probably be avoided.

**Comment by pixelbrackets** [comment]
Hey :)

> If you'd like to include a link to the updated docker image, I can change this PR to include the [URL of GHCR package](https://ghcr.io/nagimov/agendav-docker), or a [github package search query](https://github.com/search?package_type=container&q=agendav&type=RegistryPackages) (this image is still the only result there). 

Great idea :+1: 

> [Docker-hub search query](https://hub.docker.com/search?q=agendav) is full of images without `Dockerfile` source provided and should probably be avoided.

Agree :100:

**Comment by nagimov** [comment]
@pixelbrackets PR updated with GHCR link!

**Comment by pixelbrackets** [comment]
Solved, thanks for the PR!

Cherry-Picked commit 00c61f72 into `development`.

**Pull request closed without merging**
