### PR TITLE
update language configuration

### PR DESCRIPTION
**Pull request by mmoll**
This updates the languages in the configuration for languages, the PHP part has translation files for (even if all the strings are still English), so all new languages are displayed correctly in the PHP and JS parts. For the languages with non-translated PHP parts, at least the JS parts of fullcalendar.js are translated.

### CODE REVIEW

**Comment by adobo** [comment]
@mmoll not sure if this is a good idea.

While I agree with you that having at least fullcalendar UI translated is great, I think some people will find confusing that some parts of the application are translated but most are not.

What are your thoughts about that?

**Comment by mmoll** [comment]
@adobo Then we would need to take a close look into the AgenDAV translations... I can translate Czech at least to some part, I think (but didn't verify) then there's only Hungarian left as a language that has only English strings in the AgenDAV translation.

Also, as English is the fallback language anyway and often there's not 100% translated there's no way around a partly translated UI.

I did notice this initially when switching to Slovak, that one is missing the entry anyway...

**Comment by adobo** [comment]
I was reading your pull request again and I have realized that some languages which have [almost] complete translations (e.g. `pt_PT`) do not currently have a fullcalendar locale associated.

Would you mind to open a new pull request to fix this so we can discuss adding incomplete translations later?

Thank you!

**Comment by mmoll** [comment]
Not at all, #192

**Comment by mmoll** [comment]
@bartko-s BTW, if you have the time to translate another small PHP application into Slovak, it would be much appreciated. I did make a start, but am not a native speaker.

**Comment by bartko-s** [comment]
Currently I have no free time. Maybe in the near future.

**Comment by mmoll** [comment]
@bartko-s no worries :)
There's no online demo I would be aware of, but a working instance with data is coming up after a "vagrant up" in this repo.

**Pull request closed without merging**
