### PR TITLE
Allow login with HTTP Authorization header

### PR DESCRIPTION
**Pull request by Rudloff**
Hello,

We're working on a way to integrate Agendav into our web app and we want to access the JSON API but currently Agendav only supports login via the login form.
So we patched it to accept HTTP `Authorization` headers as well.
This allows us to access the API directly by providing the credentials in the request:
```bash
curl https://foo:bar@agendav.example.com/calendars
```

Is this something you would be interested in merging upstream?

Regards,

### CODE REVIEW

**Comment by adobo** [comment]
It's a really interesting approach and PR!

Do you think it could be generalized to accept additional/configurable authentication methods instead of just reading the `Authorization` header? That would be really great!

**Comment by Rudloff** [comment]
We could have an abstract authentication class that can be extended with new authentication methods.
Then in `$controllers->before()` it would try the different authentication methods enabled in the config.
What do you think?

**Comment by adobo** [comment]
That would be really great. In my opinion, defining a base authentication interface/abstract class and offering different implementations (e.g. one that uses the `Authorization` header) would be interesting.

**Comment by Rudloff** [comment]
I created a basic interface and my implementation.
Authentication methods can be enabled with the `auth.methods` parameter.

**Comment by adobo** [comment]
Sorry for the long delay! This is a good starting point. I'm merging it, we will extend it later.

Thank you!

**Comment by Glaan** [comment]
Hi,
we have follow this issue to add a CAS authentication method  hopping that this method will be continued.
But we have now a problem. The password is active 5 min and can be renewable 5 min if there is a query on our caldav server. 
But if we don't do action on agendav during more than 5 minutes, the session  for agendav is allways active unlike the saved password of the session.
I'm currently hesitating between force to activate refresh button in JavaScript  (and therefore trigger a call to calendar)  or intercept the error of access and get a new ticket for authentication.. but this need more transformation of the code... :-1: 
Any other idea,

**Pull request merged**
